twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        societe_info: '@App\Service\SocieteService'
        journee_service: '@App\Service\JourneeService'
        numberToWords: '@App\Service\NumberToWordsService'

        notify: '@App\Service\NotificationService'

    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '






when@test:
    twig:
        strict_variables: true



