twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        societe_info: '@App\Service\SocieteService'
        journee_service: '@App\Service\JourneeService'
        numberToWords: '@App\Service\NumberToWordsService'


when@test:
    twig:
        strict_variables: true



