# Commandes pour démarrer et arrêter les conteneurs Docker
docker-up:
    docker-compose up -d

docker-down:
    docker-compose down

# Commandes pour installer les dépendances PHP
install:
    composer install

# Commandes pour lancer le serveur Symfony
server:
    bin/console server:start

stop-server:
    bin/console server:stop

# Commandes pour ouvrir le projet dans PHPStorm
open:
   Program Files\JetBrains\/bin/phpstorm.sh .

# Commandes pour exécuter les tests
test:
    php bin/phpunit

# Commandes pour nettoyer le cache Symfony
clear-cache:
    bin/console cache:clear

# Commande pour exécuter les migrations
migrate:
    bin/console doctrine:migrations:migrate

# Commandes pour vérifier le style du code
lint:
    php bin/console lint:twig templates
    php bin/console lint:yaml config
    php bin/console lint:xliff translations

# Commandes pour exécuter les tâches en parallèle
parallel-tasks:
    make docker-up & \
    make server & \
    make open

# Commandes par défaut lors de l'exécution de `make`
.DEFAULT_GOAL := help

help:
    @echo "Utilisation :"
    @echo "  make docker-up              - Démarrer les conteneurs Docker"
    @echo "  make docker-down            - Arrêter les conteneurs Docker"
    @echo "  make install                - Installer les dépendances PHP"
    @echo "  make server                 - Démarrer le serveur Symfony"
    @echo "  make stop-server            - Arrêter le serveur Symfony"
    @echo "  make open                   - Ouvrir le projet dans PHPStorm"
    @echo "  make test                   - Exécuter les tests"
    @echo "  make clear-cache            - Nettoyer le cache Symfony"
    @echo "  make migrate                - Exécuter les migrations"
    @echo "  make lint                   - Vérifier le style du code"
